# Training Analysis

Ce notebook presente l'analyse des entrainements YOLO pour le projet de conduite urbaine.

Objectifs :
- comparer les premiers essais et le modele final ;
- presenter les metriques principales ;
- justifier le choix du modele retenu.

## 1. Contexte

Le scenario retenu pour le projet est la conduite urbaine avec intersections, pietons, feux et forte densite d'objets.

Le dataset utilise pour la version finale repose sur :
- un sous-ensemble filtre de 200 images pertinentes ;
- un split `train / val / test` de `140 / 30 / 30` ;
- un train augmente a 560 images/annotations.

In [1]:
import pandas as pd

results = pd.DataFrame(
    [
        {
            "model": "YOLOv8n",
            "config": "1er essai",
            "precision": 0.9070,
            "recall": 0.0550,
            "mAP50": 0.0620,
            "mAP50_95": 0.0312,
        },
        {
            "model": "YOLOv8s",
            "config": "1er essai",
            "precision": 0.3775,
            "recall": 0.1855,
            "mAP50": 0.1781,
            "mAP50_95": 0.0866,
        },
        {
            "model": "YOLOv8s",
            "config": "dataset urbain Doha - run local",
            "precision": 0.3739,
            "recall": 0.3791,
            "mAP50": 0.3263,
            "mAP50_95": 0.1557,
        },
        {
            "model": "YOLOv8s",
            "config": "test final apres entrainement Colab",
            "precision": 0.7087,
            "recall": 0.3382,
            "mAP50": 0.5471,
            "mAP50_95": 0.3211,
        },
    ]
)

results

,model,config,precision,recall,mAP50,mAP50_95
0,YOLOv8n,1er essai,0.9070,0.0550,0.0620,0.0312
1,YOLOv8s,1er essai,0.3775,0.1855,0.1781,0.0866
2,YOLOv8s,dataset urbain Doha - run local,0.3739,0.3791,0.3263,0.1557
3,YOLOv8s,test final apres entrainement Colab,0.7087,0.3382,0.5471,0.3211


## 2. Lecture des metriques

- `precision` : proportion de detections correctes parmi les detections produites.
- `recall` : proportion d'objets reels effectivement detectes.
- `mAP50` : performance globale avec un seuil IoU de 0.5.
- `mAP50_95` : version plus exigeante, moyenne sur plusieurs seuils IoU de 0.5 a 0.95.

In [2]:
results.sort_values(by="mAP50", ascending=False)

,model,config,precision,recall,mAP50,mAP50_95
3,YOLOv8s,test final apres entrainement Colab,0.7087,0.3382,0.5471,0.3211
2,YOLOv8s,dataset urbain Doha - run local,0.3739,0.3791,0.3263,0.1557
1,YOLOv8s,1er essai,0.3775,0.1855,0.1781,0.0866
0,YOLOv8n,1er essai,0.9070,0.0550,0.0620,0.0312


## 3. Analyse

Observations principales :

- `YOLOv8s` surpasse `YOLOv8n` sur les metriques globales utiles au projet.
- Le dataset urbain filtre a permis d'ameliorer nettement les resultats par rapport aux premiers essais.
- Le meilleur resultat est obtenu avec `YOLOv8s` apres entrainement final sur Colab.
- La precision finale (`0.7087`) montre que les detections produites sont souvent correctes.
- Le recall (`0.3382`) reste plus faible, ce qui signifie qu'une partie des objets presents dans la scene n'est pas encore detectee.

## 4. Conclusion

Le modele final retenu est `YOLOv8s`.

Il constitue un compromis satisfaisant pour un prototype etudiant de conduite urbaine :
- il est globalement fiable quand il detecte un objet ;
- il reste perfectible sur le rappel et sur les classes plus difficiles comme `truck`, `traffic sign` et `traffic light`.